### ISSUE TITLE
Can't connect to sparql.backend.lodlaundromat.org:80

### ISSUE THREAD

**Issue by firmao** [LOD-Laundromat/LOD-Laundromat#10]
Is the endpoint (sparql.backend.lodlaundromat.org) still alive?

Thanks in advance,

Cheers,

André Valdestilhas

**Comment by wouterbeek** [comment]
Hi @firmao ,

No the server on which the LOD Laundromat was running broke a couple of days ago :-(  I am no longer working in academia, but if somebody wants to bring LOD Laundromat back they can contact me on wouter@triply.cc to discuss what is possible.

---
Cheers,
Wouter.

**Comment by firmao** [comment]
Owww, man, thanks for the answer.
I didn't expect this situation.  I'll talk to people here in Leipzig to
find a way to keep up the LOD Laundromat as soon as possible.

I'll keep you informed.

Cheers,

André Valdestilhas

**Comment by firmao** [comment]
Just one more question: 
Is it possible to download the HDT files from http://download.lodlaundromat.org/
Or, there is another place where I can download all HDT files from LOD Laundromat?

Thanks a lot,

André Valdestilhas

**Comment by wouterbeek** [comment]
@firmao I don't have the individual HDT files anymore.  However, I did publish a snapshot some while ago into the Dutch data archive for researchers: https://easy.dans.knaw.nl/ui/datasets/id/easy-dataset:65097

**Comment by firmao** [comment]
> @firmao I don't have the individual HDT files anymore. However, I did publish a snapshot some while ago into the Dutch data archive for researchers: https://easy.dans.knaw.nl/ui/datasets/id/easy-dataset:65097
> 
> ^ I can ask the archive to send you a copy of that snapshot.

Please, can you ask this copy?

**Comment by wouterbeek** [comment]
The data archive (DANS) is preparing the files for us.  I'll let you know once they are available.

**Comment by firmao** [comment]
Thanks a lot Wouter, I really appreciate your help.
After the files arrived, If you want, I can ask people here in Leipzig to
put the files online and public.
Please, let me know if it is ok.

**Comment by firmao** [comment]
Hi Wouter,
Have you had any news from the data archive (DANS)?

Cheers,
André

**Comment by wouterbeek** [comment]
Yes, here it is: https://filesender.surf.nl/?s=download&token=988ab15e-9426-450e-8632-dc69a6ad7b19

**Comment by firmao** [comment]
Thanks a lot, I'll check it out and keep you informed.

**Comment by Anniepoo** [comment]
Wouter - is the problem just needing server space?  If so, I can help with that. emailing you.

**Comment by wouterbeek** [comment]
@Anniepoo Thanks for the generous offer.  Service space is not the main issue here.  DANS already holds a copy of the LOD Laundromat data on its server infrastructure.

**Comment by firmao** [comment]
Hi,
Is it public the LOD Laundromat at DANS, does it includes SPARQL endpoint
and the rest of the features? if yes, could you give the address or a way
to access?

Cheers,
André Valdestilhas

**Comment by wouterbeek** [comment]
@firmao https://easy.dans.knaw.nl/ui/datasets/id/easy-dataset:65097

DANS hold a dump that you have to request over email.  A bit old school, but it does work well.  I did this myself once (see an earlier message in the thread).  Unfortunately, DANS does not offer specific SPARQL/LOD features ATM.
