### ISSUE TITLE
Please do not close unresolved issues

### ISSUE THREAD

**Issue by akuckartz** [LOD-Laundromat/LOD-Laundromat#11]
Maybe someone works on them at some point in the future!

**Comment by wouterbeek** [comment]
@akuckartz This is highly unlikely, given there have been no contributions for years.  The project will be deleted or archived soon, so it does not really matter.

**Comment by akuckartz** [comment]
Why don't you simply add a note at the top of the readme?
Two messages:
1. Project is sleeping
2. New maintainers taking over would be welcome

**Comment by wouterbeek** [comment]
That's a good idea, I will try to add a description of that nature to the README soon.

**Comment by wouterbeek** [comment]
@akuckartz I've added a text to that effect to the readme file.
