### ISSUE TITLE
What is the license..?

### ISSUE THREAD

**Issue by stain** [LOD-Laundromat/LOD-Laundromat#12]
Is this project open source? https://help.github.com/en/articles/adding-a-license-to-a-repository

**Comment by wouterbeek** [comment]
Hi @stain , the LOD Laundromat is no longer being developed.

**Comment by akuckartz** [comment]
@wouterbeek Maybe he asks because he considers to continue the development? ;-)

**Comment by stain** [comment]
I may just want to borrow some code to make it into a command line or so. But without a license I am not allowed.

**Comment by wouterbeek** [comment]
@stain I've added the MIT license.
