### ISSUE TITLE
Is this project still active

### ISSUE THREAD

**Issue by ecow** [LOD-Laundromat/LOD-Laundromat#5]
Hi,
is LOD laundromat still active?

**Comment by wouterbeek** [comment]
Hi @ecow , the LOD Laundromat web service is online (http://lodlaundromat.org/), as it has been for 2,5 years now.  It processes millions of Linked Data requests each month.

However, the codebase of the LOD Laundromat, i.e., this repository, is only maintained by me ATM.  It has been proven difficult/impossible to find funding for maintaining this type of academic infrastructure.  If you have ideas for funding and/or in-kind contributions to the dev process then please drop me an email over at wouter@triply.cc

**Comment by akuckartz** [comment]
Such projects definitely need more support...

**Comment by Anniepoo** [comment]
Wouter - hit me up on IRC some time, lets talk about this.

It's senseless that LOD Laundromat not be supported.

**Comment by joernhees** [comment]
👍 would also be interested to help... i really think this project is key to LOD preservation. Many of the datasets in the LOD cloud are actually down nowadays, so having a "backup" certainly would be cool...

**Comment by wouterbeek** [comment]
@joernhees Data archiving would indeed be interesting to add.

LOD Laundromat will be used in two upcoming research projects.  Since the previous version many components have been integrated into SWI-Prolog, its Semweb library, HDT library, and ClioPatria.  LOD Laundromat 2 will be much lighter and -- hopefully -- easier to entice others to co-develop.

**Comment by e-e-e** [comment]
Sad to hear that this project has not attracted funding - it is an incredible resource and tool.

**Comment by wouterbeek** [comment]
Thanks for the kind words!

Unfortunately academic funding agencies did not agree the above comment: I was unable to find funding to sustain the LOD Laundromat project and have now left academia.

I do not doubt that some other PhD student somewhere in the world will try to build something similar at some point, either by using my code or by starting afresh.  Whatever the case may be, I wish that PhD student all the best!  I can be contacted at wouter@triply.cc

**Comment by kuzeko** [comment]
It seems that is no more possible to query the wardrobe... I assume this is the end of it?
Is there a way to mirror it?

**Comment by wouterbeek** [comment]
I've added a simple message to the top of the readme file that this project is no longer under development.

**Comment by kuzeko** [comment]
This project was great effort and an amazing resource.
Thanks for all your work.

Is the data somewhere that could be mirrored? Maybe a torrent archive?

**Comment by wouterbeek** [comment]
@kuzeko It's archived at DANS (Dutch research data institute): https://easy.dans.knaw.nl/ui/datasets/id/easy-dataset:65097

**Comment by kuzeko** [comment]
I did not know of this. Thanks.

**Comment by wouterbeek** [comment]
Also, you can browse the LOD-a-lot file, which is the graph merge over all the LOD Laundromat graphs: https://krr.triply.cc/krr/lod-a-lot/
