### ISSUE TITLE
Question about querying the Laundromat

### ISSUE THREAD

**Issue by maurodragoni** [LOD-Laundromat/LOD-Laundromat#9]
Hi,
I try to test a simple query at this link:
http://lodlaundromat.org/sparql/
and I inserted this one:

PREFIX db: <http://dbpedia.org/>
SELECT ?p ?o WHERE {
	db:FormulaOneRacing ?p ?o
}

and no results are returned.
Is it because the dbpedia ontology is not included in it or is there something wrong in the query?
Thanks.
Best,
Mauro.

**Comment by wouterbeek** [comment]
Hi @maurodragoni , thanks for using LOD Laundromat!

The SPARQL endpoint does not contain any data, only metadata.  I am still investigating approaches to make very large quantities of data queryable against low cost.  Unfortunately, ATM no such approach exists.
